language: node_js
node_js:
  - "8.8"

cache:
   directories:
      - node_modules
      - $HOME/.meteor/

before_install:
  - curl https://install.meteor.com | /bin/sh
  - npm install -g typings
before_script:
  - npm install
script:
#  - spacejam test-packages ./ --driver-package=practicalmeteor:mocha-console-runner
  - meteor test --once --driver-package meteortesting:mocha

sudo: required
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
