language: node_js
node_js:
  - "4.0"

cache:
   directories:
      - node_modules
      - $HOME/.meteor/

before_install:
  - curl https://install.meteor.com | /bin/sh
before_script:
  - meteor npm install typings --global
  - meteor npm install
script: 
#  - spacejam test-packages ./ --driver-package=practicalmeteor:mocha-console-runner
  - meteor test

sudo: required
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
